export const portfolio = {
  name: "Yash Kalani",
  role: "AI/ML & Product Engineer",
  tagline: "Building agentic AI tools and high-craft interfaces.",
  email: "kalaniya@msu.edu",
  location: "East Lansing, MI",
  github: "https://github.com/ykalani",
  linkedin: "https://www.linkedin.com/in/ykalani/",
  launcher: {
    title: "App Forge",
    subtitle: "Explore my work or spin up a small prototype from a prompt.",
    placeholder: "Search: AutoSched, logistics, music translator...",
    examples: [
      { label: "AutoSched", query: "AutoSched Syllabi Extractor" },
      { label: "Music Translator", query: "AI-Driven Music Translation Platform" },
      { label: "Logistics", query: "Michigan Logistics Case Study" },
    ],
  },
  startMenu: [
    { id: "about", label: "About Me", icon: "user" },
    { id: "projects", label: "Projects", icon: "code" },
    { id: "experience", label: "Experience", icon: "briefcase" },
    { id: "forge", label: "App Forge", icon: "zap" },
    { id: "resume", label: "Resume", icon: "file" },
    { id: "contact", label: "Contact", icon: "mail" },
    { id: "settings", label: "System Settings", icon: "sliders" },
  ],
  windows: [
    { id: "about", label: "About", glyph: "user", title: "About Me", type: "about", x: 56, y: 72, width: 420, height: 340, openByDefault: false },
    { id: "projects", label: "Projects", glyph: "code", title: "Selected Projects", type: "projects", x: 500, y: 64, width: 470, height: 380, openByDefault: false },
    { id: "experience", label: "Experience", glyph: "briefcase", title: "Experience", type: "experience", x: 96, y: 420, width: 430, height: 340, openByDefault: false },
    { id: "forge", label: "App Forge", glyph: "zap", title: "App Forge — Dynamic App Generator", type: "forge", x: 500, y: 180, width: 590, height: 410, openByDefault: false },
    { id: "contact", label: "Contact", glyph: "mail", title: "Contact", type: "contact", x: 540, y: 424, width: 420, height: 320, openByDefault: false },
    { id: "resume", label: "Resume", glyph: "file", title: "Resume", type: "resume", x: 980, y: 96, width: 380, height: 280, openByDefault: false },
    { id: "settings", label: "System Settings", glyph: "sliders", title: "System Settings", type: "settings", x: 320, y: 150, width: 460, height: 380, openByDefault: false },
  ],
  about: {
    summary: "I build agentic AI pipelines, LLM evaluation frameworks, and polished interfaces. I study Computer Science and Computational Mathematics with an AI focus at Michigan State University.",
    highlights: ["Agentic AI & MCP", "LLM evaluation", "Data engineering", "Product interfaces"],
    quickStart: ["Open Projects for selected work.", "Launch App Forge to browse this portfolio's source files.", "Open Resume to view or download my PDF."],
    stats: [
      { label: "University", value: "Michigan State" },
      { label: "Graduation", value: "May 2027" },
      { label: "Focus", value: "AI / ML" },
    ],
  },
  projects: [
    { title: "App Forge", description: "An interactive, dynamic app generator running in a mock macOS environment. Type prompts to dynamically spin up application layers.", tags: ["Gemini API", "HTML/CSS/JS", "Translucency"] },
    { title: "AutoSched", description: "Extracts lectures and exams from uploaded syllabi or screenshots, then syncs them to Google Calendar. 1st Place at Code Green Hackathon.", tags: ["React", "OpenAI API", "Tesseract OCR", "Google Calendar"] },
    { title: "Michigan Logistics Case Study", description: "Analyzed routes and recommended multi-carrier optimizations. 1st Place at Broad Datathon.", tags: ["Python", "Pandas", "XGBoost", "Power BI"] },
    { title: "AI-Driven Music Translation", description: "Translates musical parameters into Ruby code through a web editor and dockerized audio runtime.", tags: ["Next.js", "FastAPI", "Python", "Docker"] },
  ],
  experience: [
    { role: "AI/ML Engineer Intern", company: "GE Aerospace", period: "May 2026 — Aug 2026", details: "Architected agentic AI tool-calling pipelines on Bedrock with MCP servers, LLM-as-a-judge evaluation, and Databricks ingestion pipelines." },
    { role: "AI/ML Research Intern", company: "Facility for Rare Isotope Beams", period: "Aug 2025 — Present", details: "Implemented MCMC methods that reduced false positives by 23% and developed a PyTorch ResNet classifier." },
    { role: "AI/ML Engineer Intern", company: "American Axle & Manufacturing", period: "Jul 2025 — Aug 2025", details: "Built an Ignition analytics application, cleaned raw data, and integrated Dell Technologies APIs." },
    { role: "Business Automation Intern", company: "DTE Energy", period: "May 2025 — Jul 2025", details: "Developed Power Apps and Power Automate workflows and an AI-powered SharePoint agent." },
  ],
  contact: {
    intro: "Let's connect.",
    fields: [
      { label: "Email", value: "kalaniya@msu.edu", href: "mailto:kalaniya@msu.edu" },
      { label: "LinkedIn", value: "linkedin.com/in/ykalani", href: "https://linkedin.com/in/ykalani" },
      { label: "GitHub", value: "github.com/ykalani", href: "https://github.com/ykalani" },
      { label: "Profiles", value: "yash.kalani.name/profiles", href: "/profiles" },
    ],
  },
  resume: {
    summary: "Computer Science student and AI/ML engineer. View or download my current resume.",
    bullets: ["Agentic AI, LLM pipelines, PySpark, PyTorch, and React", "B.S. Computer Science, Computational Mathematics minor (AI)", "Hackathon and datathon winner"],
    pdfUrl: "/assets/Yash_Kalani_Resume-AI.pdf",
  },
};
