export const portfolio = {
  name: "Yash Kalani",
  role: "AI/ML & Product Engineer",
  tagline: "Building agentic AI tools and high-craft interfaces.",
  email: "kalaniya@msu.edu",
  location: "East Lansing, MI",
  github: "https://github.com/ykalani",
  linkedin: "https://www.linkedin.com/in/ykalani/",
  launcher: {
    title: "App Forge",
    subtitle: "Infinite project portfolio — search my work or spin up a live prototype from a prompt.",
    placeholder: "Try: AutoSched, notes app, snake game, music translator...",
    examples: [
      { label: "AutoSched", query: "AutoSched Syllabi Extractor" },
      { label: "Music Translator", query: "AI-Driven Music Translation Platform" },
      { label: "Logistics", query: "Michigan Logistics Case Study" },
      { label: "Snake", query: "Retro Snake Arcade Game" },
    ],
  },
  /**
   * Dock is projects + App Forge first. Core portfolio apps follow.
   * No socials in the dock.
   */
  dock: [
    { id: "proj-autosched", label: "AutoSched", glyph: "calendar", color: "#0a84ff", iconPath: "./assets/macOS/Calendrier_Dark.png" },
    { id: "proj-logistics", label: "Logistics", glyph: "chart", color: "#30d158", iconPath: "./assets/macOS/Finder_Dark.png" },
    { id: "proj-music", label: "Music TX", glyph: "music", color: "#bf5af2", iconPath: "./assets/macOS/Music_Dark.png" },
    { id: "forge", label: "App Forge", glyph: "zap", color: "#ffd60a", featured: true, iconPath: "./assets/macOS/Terminal_Dark.png" },
    { type: "separator" },
    { id: "about", label: "About", glyph: "user", color: "#5ac8fa", iconPath: "./assets/macOS/Safari_Dark.png" },
    { id: "experience", label: "Experience", glyph: "briefcase", color: "#ff9f0a", iconPath: "./assets/macOS/Notes_Dark.png" },
    { id: "resume", label: "Resume", glyph: "file", color: "#64d2ff", iconPath: "./assets/macOS/Calculator_Dark.png" },
    { id: "contact", label: "Contact", glyph: "mail", color: "#ff375f", iconPath: "./assets/macOS/Notes_Dark.png" },
    { id: "settings", label: "Settings", glyph: "sliders", color: "#8e8e93", iconPath: "./assets/macOS/Settings_Dark.png" },
  ],
  startMenu: [
    { id: "about", label: "About Me", icon: "user" },
    { id: "projects", label: "Projects", icon: "code" },
    { id: "experience", label: "Experience", icon: "briefcase" },
    { id: "forge", label: "App Forge", icon: "zap" },
    { id: "resume", label: "Resume", icon: "file" },
    { id: "contact", label: "Contact", icon: "mail" },
    { id: "settings", label: "System Settings", icon: "sliders" },
  ],
  windows: [
    { id: "about", label: "About", glyph: "user", title: "About Me", type: "about", x: 72, y: 56, width: 440, height: 360, openByDefault: true, accent: "#5ac8fa" },
    { id: "projects", label: "Projects", glyph: "code", title: "Selected Projects", type: "projects", x: 540, y: 64, width: 480, height: 400, openByDefault: false, accent: "#0a84ff" },
    { id: "experience", label: "Experience", glyph: "briefcase", title: "Experience", type: "experience", x: 96, y: 420, width: 450, height: 360, openByDefault: false, accent: "#ff9f0a" },
    { id: "forge", label: "App Forge", glyph: "zap", title: "App Forge — Infinite Portfolio", type: "forge", x: 480, y: 160, width: 620, height: 440, openByDefault: false, accent: "#ffd60a" },
    { id: "contact", label: "Contact", glyph: "mail", title: "Contact", type: "contact", x: 560, y: 400, width: 440, height: 380, openByDefault: false, accent: "#ff375f" },
    { id: "resume", label: "Resume", glyph: "file", title: "Resume", type: "resume", x: 980, y: 80, width: 400, height: 300, openByDefault: false, accent: "#64d2ff" },
    { id: "settings", label: "Settings", glyph: "sliders", title: "System Settings", type: "settings", x: 320, y: 140, width: 480, height: 400, openByDefault: false, accent: "#8e8e93" },
    {
      id: "proj-autosched",
      label: "AutoSched",
      glyph: "calendar",
      title: "AutoSched",
      type: "project",
      projectId: "autosched",
      x: 180,
      y: 100,
      width: 460,
      height: 340,
      openByDefault: false,
      accent: "#0a84ff",
    },
    {
      id: "proj-logistics",
      label: "Logistics",
      glyph: "chart",
      title: "Michigan Logistics",
      type: "project",
      projectId: "logistics",
      x: 240,
      y: 140,
      width: 460,
      height: 340,
      openByDefault: false,
      accent: "#30d158",
    },
    {
      id: "proj-music",
      label: "Music TX",
      glyph: "music",
      title: "AI Music Translation",
      type: "project",
      projectId: "music",
      x: 300,
      y: 180,
      width: 460,
      height: 340,
      openByDefault: false,
      accent: "#bf5af2",
    },
  ],
  about: {
    summary: "I build agentic AI pipelines, LLM evaluation frameworks, and polished interfaces. I study Computer Science and Computational Mathematics with an AI focus at Michigan State University.",
    highlights: ["Agentic AI & MCP", "LLM evaluation", "Data engineering", "Product interfaces"],
    quickStart: [
      "Click a project icon in the dock to open it.",
      "Launch App Forge to search my work or generate a live prototype.",
      "Open Resume to view or download my PDF.",
    ],
    stats: [
      { label: "University", value: "Michigan State" },
      { label: "Graduation", value: "May 2027" },
      { label: "Focus", value: "AI / ML" },
    ],
  },
  projects: [
    {
      id: "autosched",
      title: "AutoSched",
      description: "Extracts lectures and exams from uploaded syllabi or screenshots, then syncs them to Google Calendar. 1st Place at Code Green Hackathon.",
      tags: ["React", "OpenAI API", "Tesseract OCR", "Google Calendar"],
      highlight: "1st Place · Code Green Hackathon",
    },
    {
      id: "logistics",
      title: "Michigan Logistics Case Study",
      description: "Analyzed routes and recommended multi-carrier optimizations. 1st Place at Broad Datathon.",
      tags: ["Python", "Pandas", "XGBoost", "Power BI"],
      highlight: "1st Place · Broad Datathon",
    },
    {
      id: "music",
      title: "AI-Driven Music Translation",
      description: "Translates musical parameters into Ruby code through a web editor and dockerized audio runtime.",
      tags: ["Next.js", "FastAPI", "Python", "Docker"],
      highlight: "Full-stack audio pipeline",
    },
    {
      id: "forge",
      title: "App Forge",
      description: "Infinite project portfolio: type a prompt and spin up interactive app windows inside yashOS. Gemini-backed with offline template fallback.",
      tags: ["Gemini API", "HTML/CSS/JS", "Window manager"],
      highlight: "Live generative desktop apps",
    },
  ],
  experience: [
    { role: "AI/ML Engineer Intern", company: "GE Aerospace", period: "May 2026 — Aug 2026", details: "Architected agentic AI tool-calling pipelines on Bedrock with MCP servers, LLM-as-a-judge evaluation, and Databricks ingestion pipelines." },
    { role: "AI/ML Research Intern", company: "Facility for Rare Isotope Beams", period: "Aug 2025 — Present", details: "Implemented MCMC methods that reduced false positives by 23% and developed a PyTorch ResNet classifier." },
    { role: "AI/ML Engineer Intern", company: "American Axle & Manufacturing", period: "Jul 2025 — Aug 2025", details: "Built an Ignition analytics application, cleaned raw data, and integrated Dell Technologies APIs." },
    { role: "Business Automation Intern", company: "DTE Energy", period: "May 2025 — Jul 2025", details: "Developed Power Apps and Power Automate workflows and an AI-powered SharePoint agent." },
  ],
  contact: {
    intro: "Let's connect. Socials and profiles live here — not in the dock.",
    fields: [
      { label: "Email", value: "kalaniya@msu.edu", href: "mailto:kalaniya@msu.edu" },
      { label: "LinkedIn", value: "linkedin.com/in/ykalani", href: "https://linkedin.com/in/ykalani" },
      { label: "GitHub", value: "github.com/ykalani", href: "https://github.com/ykalani" },
      { label: "Profiles", value: "yash.kalani.name/profiles", href: "/profiles" },
    ],
  },
  resume: {
    summary: "Computer Science student and AI/ML engineer. View or download my current resume.",
    bullets: ["Agentic AI, LLM pipelines, PySpark, PyTorch, and React", "B.S. Computer Science, Computational Mathematics minor (AI)", "Hackathon and datathon winner"],
    pdfUrl: "/assets/Yash_Kalani_Resume-AI.pdf",
  },
};
